import { ApiProperty } from '@nestjs/swagger';

export class ChatResponseDataDto {
  @ApiProperty({
    example:
      'Modular monorepos improve code reuse, maintain type safety across services, and accelerate development.',
    description: 'The response text generated by the AI model provider',
  })
  response!: string;
}
