import { ApiProperty } from '@nestjs/swagger';

export class ChatResponseDataDto {
  @ApiProperty({
    example: 'conv_8f9a2b1c3d4e5f6a',
    description: 'Unique conversation ID tracking the chat context',
  })
  conversationId!: string;

  @ApiProperty({
    example:
      'Modular monorepos improve code reuse, maintain type safety across services, and accelerate development.',
    description: 'The response text generated by the AI model provider',
  })
  response!: string;
}
